spring:
  profiles: dev
server:
  port: 8000
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: password
    key-store-type: JKS
    key-alias: linkedin
    key-password: password
---
server:
  port: 9000

#to tell hibernate not to generate data bcuz we are going to use our data.sql
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://localhost:3306/springboot2_essential_training
    username: morteza
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update




