spring:
  profiles: dev
server:
  port: 8000
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: password
    key-store-type: JKS
    key-alias: linkedin
    key-password: password
---
spring:
  profiles: test
server:
  port: 9000
